# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
   TWITTER_CONSUMER_KEY: 2jcrON1UELLYAUQG1b5lcI9Q9
   TWITTER_CONSUMER_SECRET: 1SYCOsMLrlj6M4bQpbaVsYTAQkbvm9DdCP8XpkzN7dbMHMkrsB
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
