AWS_SECRET_ACCESS_KEY: "3QrM1NWsHFnfXIOINLiNaHl8fBPOrgrfyzPhTebi"
AWS_ACCESS_KEY_ID: "AKIAIGMZZXXXMA4XPGHA"
S3_BUCKET_NAME: "kevinsimagebucket"
TWITTER_CONSUMER_KEY: "2jcrON1UELLYAUQG1b5lcI9Q9"
TWITTER_CONSUMER_SECRET: "1SYCOsMLrlj6M4bQpbaVsYTAQkbvm9DdCP8XpkzN7dbMHMkrsB"
